### ISSUE TITLE
Course with messages showing "Not logged in" and no messages

### ISSUE THREAD

**Issue by allen75570** [OSCELOT/MyMessages#1]
Good afternoon, 
We have My Messages V 2.2.1 installed in our SaaS Production instance of Blackboard Release 3300.0.2. We have identified the following weird message:
![mymessages_error](https://user-images.githubusercontent.com/18555422/37984874-f4292682-31e6-11e8-85e4-4dc4fae01378.PNG)
If you click on the course, there are actually 3 unread messages. I've never seen that issue before. 
I see that you recently updated to Version 3. Will an update resolve this issue?
Thanks, 
Julia Allen
jallen@tamut.edu

**Comment by UNMLMS** [comment]
Hello Julia,
  My Messages V 2.2.1 is no longer supported.
You are welcome to install (suggest on a testserver) this rebuild (please read README file first) to see if it resolves this issue.
Please reply here to let us know if it resolves this issue.

**Comment by dhjackson** [comment]
We also had this issue show up and found that in our case when the course showed "not Logged in" there were "unknown" senders on the list which we verified was the student preview user where data had been cleared on exit. Once we got Bb to add the PK value of the instructor of record to the message table - "not logged in" went away.
